services:
  dind:
    image: docker:dind  # Updated to the latest stable version
    privileged: true
    volumes:
      - dind-storage:/var/lib/docker
      - ${PWD}:/workspace # Use project directory as workspace
    environment:
      DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
    ports:
      - "2376:2375"  # Changed the host port to 2376 to avoid conflict
    command: ["dockerd-entrypoint.sh", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    deploy:
      replicas: ${USE_DIND:-0} # Only start dind if USE_DIND is set to 1

  k6:
    image: grafana/k6
    volumes:
      - ${PWD}:/workspace # Use project directory as workspace
      - ${PWD}/k6-tests:/k6-tests # Use relative path for test files
    depends_on:
      - dind
    entrypoint: ["k6", "run", "/k6-tests/test.js"]

volumes:
  dind-storage:
  workspace: # Ensure the workspace volume is defined

